### ISSUE TITLE
Button 'Lets Create Awesome Website' is not working

### ISSUE THREAD

**Issue by lunoos** [Iamdivyak/portfolio#10]
I was going through your portfolio and noticed that the button 'Lets Create Awesome Website' is not working.
Ideally, when i click on the button it should have navigated to 'Get in touch' section of the page.

I would like to work on this issue can you please assign it to me with hackoctoberfest tag.

Thanks.

**Comment by DeepRahangdale** [comment]
@Iamdivyak  assign me this ..
