### ISSUE TITLE
issue: spelling typos

### ISSUE THREAD

**Issue by spacesie** [Iamdivyak/portfolio#11]
# **Typo Corrections in Portfolio Text**

## **Issue description:**
**The following typo issues need to be addressed in the provided text:**

1. "experties" should be corrected to "expertise."
2. "Massege" should be corrected to "Message."
3. "GAT IN TOUCH" should be changed to "GET IN TOUCH."
4. "Frond-End" should be corrected to "Front-End."

**These spelling typos are found across all web pages that include:**
- index.html
- projects.html
- services.html
- about.html
- pricing.html

**Comment by Iamdivyak** [comment]
you can work on this issue now:)
thanks for correcting
