### ISSUE TITLE
Spelling mistake in SKILLS section. 

### ISSUE THREAD

**Issue by gauravsingh1281** [Iamdivyak/portfolio#16]
<img width="960" alt="Screenshot 2023-10-18 154150" src="https://github.com/Iamdivyak/portfolio/assets/85905403/d7da5d1f-4519-416c-ac82-e56a81cefdd3">

**Comment by gauravsingh1281** [comment]
@Iamdivyak Please assign this issue to me under hacktoberfest label.

**Comment by kshitizvardhan** [comment]
@Iamdivyak Please assign this issue to me
Thank You
