### ISSUE TITLE
Grammatical Errors 

### ISSUE THREAD

**Issue by bilaljaved01** [Iamdivyak/portfolio#25]
I saw some grammatical errors in the website which might leave bad impression on potential client or employer, i wish to work on that and improvise it with more effective tag lines, Assign this to me under hacktoberfest

**Comment by Iamdivyak** [comment]
can you provide a screenshot of the grammatical errors?

**Comment by sanket2323** [comment]
Hey i would like to find the issues and would like to contribute to this issue

**Comment by bilaljaved01** [comment]
![Screenshot_2023-10-20-19-59-22-632_org.mozilla.firefox-edit.jpg](https://github.com/Iamdivyak/portfolio/assets/88791280/19b85d55-9a8a-463f-bdf5-a3fab27ed4d5)

![Screenshot_2023-10-20-19-58-19-806_org.mozilla.firefox-edit.jpg](https://github.com/Iamdivyak/portfolio/assets/88791280/21156357-65d5-4597-ac1c-b83c0c4fda71)

![Screenshot_2023-10-20-19-59-09-471_org.mozilla.firefox-edit.jpg](https://github.com/Iamdivyak/portfolio/assets/88791280/366a38f7-e604-4e08-8e18-3dc195b5099a)

**Comment by bilaljaved01** [comment]
These are not grammatically correct and can be changed to impact the viewer more effectively
