### ISSUE TITLE
add back-to-top button

### ISSUE THREAD

**Issue by Iamdivyak** [Iamdivyak/portfolio#26]
Here is the design for the back-to-top button.
[figma design](https://www.figma.com/file/wKcuUSuG9uEbaXL4TytRzG/my-profile%2Fportfolio-design?type=design&node-id=0%3A1&mode=design&t=ZoUYJFI5oRP7RJiR-1)

if you have any better alternative. please share with us. 
we highly appreciate it.

**Comment by madmaxWMFU** [comment]
Hi! I can try this. Can you assign it for me?
