### ISSUE TITLE
make pricing page using figma design 

### ISSUE THREAD

**Issue by Iamdivyak** [Iamdivyak/portfolio#28]
[figma design](https://www.figma.com/file/wKcuUSuG9uEbaXL4TytRzG/my-profile%2Fportfolio-design?type=design&node-id=1205%3A225&mode=design&t=eu8fvYPnP69DOAlr-1)

take a look at the page name "pricing page" in the design and code along

**Comment by urzahmed** [comment]
Yeah! I can work on this for sure. 
Could you assign me this issue under hacktoberfest-accepted, hacktoberfest tag

**Comment by Blink29** [comment]
i can you assign this to me pls and also add hacktober-accepted tag as i have completed it

<img width="1470" alt="Screenshot 2023-10-21 at 6 34 25 PM" src="https://github.com/Iamdivyak/portfolio/assets/115066832/9d31d099-d1f1-457a-85aa-4b9eea8969e8">

**Comment by Blink29** [comment]
@Iamdivyak

**Comment by Iamdivyak** [comment]
Hey @Blink29 you have done great. if @urz-ahmed does not complete this issue in 3-4 days, then I will assign you.
But for now, you can work with other issues like issue no: #3 or #6

**Comment by urzahmed** [comment]
hi i have made all changes which you have described this issue. could you merge it your main repo?
