### ISSUE TITLE
fix active link

### ISSUE THREAD

**Issue by Iamdivyak** [Iamdivyak/portfolio#3]
when we go to the About page the navbar "about" should have a darker color.

**Comment by yuyujijin** [comment]
hi, can i work on this ?

**Comment by Obikaviola** [comment]
Can I be assigned this task?

**Comment by Iamdivyak** [comment]
hi @Obikaviola 👋🏻. any updates?

**Comment by Blink29** [comment]
<img width="1470" alt="Screenshot 2023-10-21 at 7 46 10 PM" src="https://github.com/Iamdivyak/portfolio/assets/115066832/66826974-57e1-47b0-9273-c2360bd94b31">
assign this to me under hacktoberfest accepted please

**Comment by Iamdivyak** [comment]
assigned @Blink29. 
make sure it also works for the pricing and project section

**Comment by Rohitsonvane88** [comment]
assign this to me under hacktoberfest accepted please
