### ISSUE TITLE
FIX - Highlighting the navbar according to current page.

### ISSUE THREAD

**Issue by tharanithar-r** [Iamdivyak/portfolio#35]
When we switch to another page like about, pricing and projects , in the navbar 'home' only gets bold and highlighted. I am interested in highlight the navbar according to the current page so that user can navigate without any confuse. Kindly issue this to me.

https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/145109919/6c9b1e78-547d-448b-b1ec-fe0910c0fdb7

**Comment by Iamdivyak** [comment]
someone is already working on it. issue no.: #3
