### ISSUE TITLE
form is not working properly

### ISSUE THREAD

**Issue by weberankit** [Iamdivyak/portfolio#38]
I have tried to submit the form but it's not working I can fix this .

approach:-
I will use some free email-based service so that you get form details directly on your email

could you assign me this issue under the Hactoberfest tag?
![image](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/94105514/f6ee6005-2fb6-49d4-96ee-1230dbb02546)

**Comment by Iamdivyak** [comment]
assigned @weberankit. happy codding:)

**Comment by weberankit** [comment]
@Iamdivyak I am using formSubmit so could you plz provide your email id
![image](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/94105514/e3e58a1c-0b11-45e9-8f4b-b96fc506ec8a)

**Comment by weberankit** [comment]
@Iamdivyak  I have also added some awesome form  vailidation checks plz look out for this

https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/94105514/663e10f3-f2e3-41de-bf96-6bb750a950c0

**Comment by weberankit** [comment]
@Iamdivyak  can I use this kumaridivya2796@gmail.com ?? also you have to activate the link an email will be sent from formSubmit

**Comment by Iamdivyak** [comment]
yes, u can use that email.
I'm glad you're also validating it. thankyou:)

**Comment by weberankit** [comment]
@Iamdivyak plz check pr #42

**Comment by weberankit** [comment]
completed
