### ISSUE TITLE
Twitter logo 

### ISSUE THREAD

**Issue by himanshu07gupta** [Iamdivyak/portfolio#39]
This logo is old, which shows that the profile is not updated. I will change the logo with a new icon.
can you assign this task to me?
![image](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/97677063/46a1e819-eed8-4bc0-a731-14c0a3d46afb)

**Comment by Iamdivyak** [comment]
sure
happy coding:)

**Comment by himanshu07gupta** [comment]
> sure happy coding:)
Thank you
