### ISSUE TITLE
Hire me button

### ISSUE THREAD

**Issue by himanshu07gupta** [Iamdivyak/portfolio#41]
The 'Hire Me' button is not linked to any URL.

Suggested Solution:

I will add your email address, which will directly redirect messages to you, to any employee or HR.

![image](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/97677063/9cd3f7df-3cd2-46de-8804-8bcc53e06ef0)

can you please assign this task to me so that i can start working on it.

**Comment by Iamdivyak** [comment]
assigned @himanshu07gupta
