### ISSUE TITLE
Responsive Pricing Card Wrapping on Half-Screen Width

### ISSUE THREAD

**Issue by heeba-khan** [Iamdivyak/portfolio#46]
Rectified the issue of vertical stacking of pricing cards occurring prematurely, even when the screen width reduced by half, resulting in an unsymmetrical layout. This was resolved through the implementation of custom CSS styles within the 'style.css' file to ensure a more visually balanced and responsive design. The below picture is before the changes were made :

![Screenshot (107)](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/111532086/6f8f8b18-8fa5-4117-bcb0-f8754664232a)

After I did some changes in style.css file by adding some styles, the pricing card now looked like this :

![Screenshot (108)](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/111532086/d1b0706b-6426-4868-ac25-76f14bdf93db)

**Comment by Iamdivyak** [comment]
here is the design [figma design](https://www.figma.com/file/wKcuUSuG9uEbaXL4TytRzG/my-profile%2Fportfolio-design?type=design&node-id=0%3A1&mode=design&t=TgSPcyjNpZr9n8YT-1)

can u make that pricing page design?

**Comment by heeba-khan** [comment]
Yes, I can.

**Comment by Iamdivyak** [comment]
assigned @heeba-khan

**Comment by heeba-khan** [comment]
I accept the assignment.

**Comment by heeba-khan** [comment]
@Iamdivyak There is an issue coming. Whenever I am clicking on inspect element, the changes that I have made are showing :

![Screenshot (109)](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/111532086/7829f7e4-f450-4b97-957d-e8f02c9e2e75)


But when I am removing the inspect element, then all the changes are gone. Why is it happening ? Can you suggest something?

![Screenshot (110)](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/111532086/05a15b24-cc44-486e-b481-3e161de09943)

**Comment by Iamdivyak** [comment]
May be you are putting your css styles under media query

**Comment by heeba-khan** [comment]
OK I will look into it.

**Comment by Iamdivyak** [comment]
any updates? @heeba-khan

**Comment by heeba-khan** [comment]
I am sorry but I tried my best. If you want I can send you the CSS styles
that I had applied and it was matching your figma style as well.

**Comment by suhas-sensei** [comment]
i'd be happy if i'm assigned this issue @Iamdivyak

**Comment by Iamdivyak** [comment]
sure @suhas-sensei  :)

**Comment by suhas-sensei** [comment]
please review the pr @Iamdivyak :3
