### ISSUE TITLE
Problem with the borders on the skills section on homepage

### ISSUE THREAD

**Issue by nilis24** [Iamdivyak/portfolio#47]
Hi! It's the first time I visited this repository and I visited the website. I detected that there is a problem with the borders on the skills sections on the homepage, and it is that the borders are not well placed, there are places where they are missing or there are places where there are too many, that is to say, there is no logical order in this. I attach a picture to show what I mean:

<img width="1094" alt="image" src="https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/57112395/3a6f775f-1617-4289-ba66-2c755c1b9e27">

I can solve this issue, so please assign it to me 🙏

**Comment by Iamdivyak** [comment]
assigned @nilis24

**Comment by nilis24** [comment]
Thank you!! 🤩🤩

**Comment by nilis24** [comment]
Do you like it like this? I thought you only wanted to put the inside borders but it is difficult to make this design responsive. So I came up with this to solve it, what do you think?
<img width="1078" alt="image" src="https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/57112395/0c0ee34c-f465-47aa-8efb-5ef28f6b8594">

**Comment by Iamdivyak** [comment]
this design is too easy. not so interesting, come up with another alternatives

**Comment by Iamdivyak** [comment]
https://www.figma.com/file/wKcuUSuG9uEbaXL4TytRzG/my-profile%2Fportfolio-design?type=design&node-id=1383%3A2&mode=design&t=1XdljjDrM0iKJm3A-1

I HAVE MADE ANOTHER COPY OF THE DESIGN AND MADE SOME CHANGES THERE. YOU CAN USE THAT IN YOUR STYLES

**Comment by Iamdivyak** [comment]
pr #67
