### ISSUE TITLE
On hover services card, it resize entire service container also

### ISSUE THREAD

**Issue by Honeshwar** [Iamdivyak/portfolio#54]
hi, assign me this task:
Issue: In services section , we having services card on hover this card  entire service section also get resize with card resize:

**See Here:**

https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/73346917/6de0a2c3-d714-45c0-bb38-0d3844ff3732

also add label hacktoberfest

**Comment by Iamdivyak** [comment]
assigned @Honeshwar
