### ISSUE TITLE
add a better hover effect animation

### ISSUE THREAD

**Issue by Iamdivyak** [Iamdivyak/portfolio#56]
I just wanted to let you know that you can discuss the design idea here. create a design in Figma and share that here before coding.

The current button hover effect is the king of inconsistent

**Comment by Bhavya-Chawla** [comment]
Hello @Iamdivyak , Your project looks innovative and interesting. Can you assign this issue to me? I would really like to work on it.

**Comment by Iamdivyak** [comment]
hey @Bhavya-Chawla. share your idea a bit. if you have designed a button, share that in here
