### ISSUE TITLE
Enhancement in area of expertise

### ISSUE THREAD

**Issue by Iamdivyak** [Iamdivyak/portfolio#57]
> current design
<img width="445" alt="image" src="https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/102896170/c58dd85e-d669-42a0-b0de-5088a3143ae5">

> goal
<img width="470" alt="image" src="https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/102896170/b94c4a47-6ab2-4084-9ec3-ca91ceab0d4d">

visite the [figma design](https://www.figma.com/file/wKcuUSuG9uEbaXL4TytRzG/my-profile%2Fportfolio-design?type=design&node-id=1383%3A2&mode=design&t=CXUXCcOw8BmNmouO-1) to learn more

**Comment by manan18** [comment]
Your project looks interesting and innovative , I would really like to work on it.
Can you please assign me this issue?

**Comment by Iamdivyak** [comment]
thank you. give this repo a star as an appreciation:)

**Comment by manan18** [comment]
sure :)

**Comment by manan18** [comment]
![image](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/96439888/70c3bdd5-7766-40fd-b7e3-ec50e80790fe)
Does this work?

**Comment by manan18** [comment]
I've initiated a PR #60. Please have a look.

**Comment by Akshit203** [comment]
I would like to present an alternative design, so how about this ?
![Screenshot 2023-10-28 125638](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/99758311/ee9b55b2-d4c8-428a-86c1-6c8e00cbce28)

**Comment by Iamdivyak** [comment]
Hi @Akshit203 I like your design, do you want to work on this?

**Comment by Akshit203** [comment]
Yes

**Comment by Iamdivyak** [comment]
Ok, I'm assigning this to you. please use grid instead of flex. This would be easier for the required layout.
 
The required layout should be 4 * 3 in desktop view, 3 * 4 in tablet view, and 2 * 6 in mobile view.

**Comment by Akshit203** [comment]
Hi @Iamdivyak 
I've initiated a PR #66

**Comment by Akshit203** [comment]
I've initiated a New PR #67

**Comment by Iamdivyak** [comment]
pr #67
