### ISSUE TITLE
make footer responsive

### ISSUE THREAD

**Issue by Iamdivyak** [Iamdivyak/portfolio#6]

**Comment by Raghu1124** [comment]
Please assign this issue to me, I will amke a responsive footer for this issue

**Comment by Raghu1124** [comment]
and add hactorberfest label

**Comment by Iamdivyak** [comment]
done.  happy coding

**Comment by Iamdivyak** [comment]
hello @Raghu1124 any update?!!

**Comment by Raghu1124** [comment]
> hello @Raghu1124 any update?!!

sorry @Iamdivyak , i tried to make footer responsive but not able to make it, and i don't think i can make it responsive.
Sorry and thank you for your valuable time

**Comment by Iamdivyak** [comment]
thanks for your honest answer. you will learn it in no time.

**Comment by Blink29** [comment]
@Iamdivyak can you assign this to me and please tell what find of footer you want?

**Comment by Sreyasree-001** [comment]
can I work on this issue?

**Comment by weberankit** [comment]
@Iamdivyak  can I work on this ??

**Comment by Iamdivyak** [comment]
Hey @Blink29 I have designed the footer.
have a look
https://www.figma.com/file/wKcuUSuG9uEbaXL4TytRzG/my-profile%2Fportfolio-design?type=design&node-id=1335%3A8&mode=design&t=whtbaJrLcR7HtRzr-1

**Comment by Iamdivyak** [comment]
hey @Blink29 any updates?!!

**Comment by Iamdivyak** [comment]
> @Iamdivyak can I work on this ??

sure, I am assigning this issue to you.
