### ISSUE TITLE
Wrong background color on hover

### ISSUE THREAD

**Issue by Honeshwar** [Iamdivyak/portfolio#63]
On hovering on Let’s create an awesome website button:

1. background color according to figma design is different as current background color on hover

**Current**

![Divya Kumari _ Portfolio - Google Chrome 26-10-2023 22_16_44](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/73346917/3e5fedad-9582-4ab2-b6d1-972ca3e16bc6)

**In figma**

![Divya Kumari _ Portfolio - Google Chrome 26-10-2023 22_37_04](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/73346917/49012f2f-5b40-4989-9121-4f33dcf63c34)

**Note : Add hacktoberfest label**

Assign me I will do it:

Thank you 😃

**Comment by Iamdivyak** [comment]
I was just experimenting with other button designs. I like the current one better. but can you make smooth hover effect?

**Comment by Iamdivyak** [comment]
Like currently when we hover, Button changes in gradient without any transition/animation. I am assigning you to make a smooth transition in the buttons
