### ISSUE TITLE
Make services card same as in figma design

### ISSUE THREAD

**Issue by Honeshwar** [Iamdivyak/portfolio#64]
I see in figma design the services card is different:
1. having some box shadow,
2. text should be medium size.

**Current**

![Divya Kumari _ Portfolio - Google Chrome 26-10-2023 22_16_34](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/73346917/824762b3-fe14-4bb8-b9e9-b9f852ace7ba)

**In figma**

![Divya Kumari _ Portfolio - Google Chrome 26-10-2023 22_37_45](https://github.com/Iamdivyak/Freelance-Web-Developer-Portfolio-Template/assets/73346917/2738296c-fb75-4270-a09d-daeffbe27d12)

**Note : Add hacktoberfest label**

Assign me

Thank you 😃

**Comment by Iamdivyak** [comment]
I like the current one better. I'm sorry I forgot to make changes in Figma design
