### ISSUE TITLE
Footer UI Enhancements

### ISSUE THREAD

**Issue by Jaspreet099** [Iamdivyak/portfolio#9]
### This thing overall enhances the UI and UX of footer links
- Instead of everything in the centre, all should be aligned to the left because its easy to read and follow along
- rather than using this shadow the underline effect will make it clean 

Assign this issue to me, Thanks 

If you want to add something let me know

<img width="317" alt="Screenshot 2023-10-17 at 11 17 38 PM" src="https://github.com/Iamdivyak/portfolio/assets/75212002/f7d12562-728d-41e4-b26c-db6680710ad2">

**Comment by Raghu1124** [comment]
Please assign this issue to me, Thanks
